# This is a basic workflow to help you get started with Actions

name: Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  API_Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matt-ball/newman-action@master
        with:
        node-version: '14.x'
           run: npm run test-positive
